CREATE TABLE IF NOT EXISTS `agent_decision_log` (
  `id`                bigint unsigned NOT NULL AUTO_INCREMENT,
  `trace_id`          varchar(64)     NOT NULL COMMENT '请求追踪ID',
  `source_service`    varchar(64)     NOT NULL DEFAULT '' COMMENT '来源服务: agent/gateway/business',
  `tenant_id`         varchar(64)     NOT NULL DEFAULT '' COMMENT '租户ID',
  `owner_user_id`     varchar(64)     NOT NULL DEFAULT '' COMMENT '归属用户ID',
  `session_id`        varchar(128)    NOT NULL DEFAULT '' COMMENT '会话ID',
  `agent_id`          varchar(64)     NOT NULL DEFAULT '' COMMENT '智能体ID',
  `user_query`        text            NOT NULL COMMENT '用户原始查询',
  `intent_type`       varchar(64)     NOT NULL DEFAULT '' COMMENT '意图分类结果',
  `selected_tool_list` json           COMMENT '工具列表',
  `decision_reason`   text            COMMENT '模型决策理由',
  `branch_type`       varchar(32)     NOT NULL DEFAULT '' COMMENT '分支: RAG/DIRECT_ANSWER/TOOL_CALL/REJECT',
  `plan_steps`        json            COMMENT '规划步骤',
  `tool_call_times`   int             NOT NULL DEFAULT 0 COMMENT '工具调用总次数',
  `tool_retry_times`  int             NOT NULL DEFAULT 0 COMMENT '工具重试次数',
  `agent_status`      varchar(32)     NOT NULL DEFAULT '' COMMENT '状态: SUCCESS/FAIL/LOOP/TIMEOUT',
  `cost_time_ms`      int             NOT NULL DEFAULT 0 COMMENT '执行总耗时(ms)',
  `model_version`     varchar(64)     NOT NULL DEFAULT '' COMMENT '模型版本',
  `error_message`     text            COMMENT '失败错误信息',
  `create_time`       datetime        NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`),
  KEY `idx_session_id` (`session_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent决策行为日志';
