CREATE TABLE IF NOT EXISTS `rag_retrieval_log` (
  `id`                bigint unsigned NOT NULL AUTO_INCREMENT,
  `trace_id`          varchar(64)     NOT NULL COMMENT '请求追踪ID',
  `source_service`    varchar(64)     NOT NULL DEFAULT 'agent' COMMENT '来源服务',
  `tenant_id`         varchar(64)     NOT NULL DEFAULT '' COMMENT '租户ID',
  `owner_user_id`     varchar(64)     NOT NULL DEFAULT '' COMMENT '归属用户ID',
  `session_id`        varchar(128)    NOT NULL DEFAULT '' COMMENT '会话ID',
  `agent_id`          varchar(64)     NOT NULL DEFAULT '' COMMENT '智能体ID',
  `query_text`        text            NOT NULL COMMENT '原始查询',
  `rewrite_text`      text            COMMENT '改写后查询',
  `retrieval_topk`    int             NOT NULL DEFAULT 0 COMMENT 'TopK配置',
  `retrieval_count`   int             NOT NULL DEFAULT 0 COMMENT '实际召回切片数',
  `source_docs`       json            COMMENT '命中证据',
  `rerank_scores`     json            COMMENT '重排分数',
  `empty_retrieval`   tinyint         NOT NULL DEFAULT 0 COMMENT '是否空召回 0/1',
  `retrieval_cost_ms` int             COMMENT '检索总耗时(ms)',
  `retrieval_stages`  json            COMMENT '各阶段',
  `rag_strategy_version` varchar(64)  NOT NULL DEFAULT '' COMMENT 'RAG策略版本',
  `create_time`       datetime        NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_session_id` (`session_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='RAG检索日志';
